// Auto-generated from router/index.ts
export type RouteName =
  'AdminCryptoMatching' |
  'AdminGlossary' |
  'AdminMessagerie' |
  'AdminNews' |
  'AdminOrders' |
  'AdminProducts' |
  'AdminPromoCodes' |
  'AdminSessions' |
  'AdminStats' |
  'AdminTopics' |
  'AdminUsers' |
  'about' |
  'access-denied' |
  'actualite-detail' |
  'actualites' |
  'auth-callback' |
  'auth-login' |
  'auth-register' |
  'auth-reset' |
  'cart' |
  'catalogue' |
  'cgu' |
  'checkout' |
  'checkout-confirmation' |
  'cookies' |
  'crypto-guide' |
  'email-sent' |
  'faq' |
  'favorites' |
  'glossaire' |
  'glossaire-detail' |
  'home' |
  'mentions-legales' |
  'mfa-challenge' |
  'mfa-setup' |
  'newsletter-confirm' |
  'newsletter-unsubscribe' |
  'nurturing-optout' |
  'order-detail' |
  'orders' |
  'politique-confidentialite' |
  'product-detail' |
  'profil' |
  'reconstitution' |
  'ressource-detail' |
  'ressources' |
  'status' |
  'track-order' |
  'update-password' |
  'update-password-success'
