import fs from 'fs'
import path from 'path'

export function generateRouteNamesUnion(baseDir: string) {
  const routerPath = path.resolve(baseDir, 'src/router/index.ts')
  const outputPath = path.resolve(baseDir, 'src/router/route-name.ts')

  const content = fs.readFileSync(routerPath, 'utf-8')

  // Match toutes les valeurs de `name: '...'`
  const routeNames = Array.from(content.matchAll(/name:\s*['"`]([^'"`]+)['"`]/g), (match) => match[1])

  // Supprime doublons, trie, et génère un type TS
  const uniqueNames = [...new Set(routeNames)].sort()
  const union = `// Auto-generated from router/index.ts
export type RouteName =
  ${uniqueNames.map((name) => `'${name}'`).join(' |\n  ')}
`

  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, union, 'utf-8')

  console.log(`✅ RouteName generated in ${outputPath} (${uniqueNames.length} routes)`)
}

export function generateGlobalComponents(baseDir: string) {
  const vueExt = /\.vue$/
  const srcDirs = [path.resolve(baseDir, 'designSystem/src')]

  const walkVueFiles = (dir: string): string[] => {
    return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) return walkVueFiles(fullPath)
      if (entry.isFile() && vueExt.test(entry.name)) {
        return [fullPath]
      }
      return []
    })
  }

  const files = srcDirs.flatMap(walkVueFiles)

  const declarations = files.map((filePath) => {
    const componentName = path.basename(filePath, '.vue').replace(/(^\w|-\w)/g, (m) => m.replace('-', '').toUpperCase())
    const relativePath = './' + path.relative(path.resolve(baseDir, 'src'), filePath).replace(/\\/g, '/')
    return `    ${componentName}: typeof import('${relativePath}')['default']`
  })

  const output = `// Auto-generated by vite.config.ts
export {}

declare module 'vue' {
  export interface GlobalComponents {
${declarations.sort().join('\n')}
  }
}
`

  fs.writeFileSync(path.resolve(baseDir, 'src/global-components.d.ts'), output, 'utf-8')
}

export function generateIconsList(dirname: string) {
  const iconsDirBold = path.resolve(dirname, 'designSystem/src/fondation/icons/bold')
  const iconsDirOutline = path.resolve(dirname, 'designSystem/src/fondation/icons/outline')
  const boldIcons = fs.readdirSync(iconsDirBold).map((file) => file.replace('.svg', ''))
  const outlineIcons = fs.readdirSync(iconsDirOutline).map((file) => file.replace('.svg', ''))
  const combinedIcons = [...new Set([...boldIcons, ...outlineIcons])]
  const outputPath = path.resolve(dirname, 'designSystem/src/fondation/icons/iconsList.ts')
  const fileContent = `
    export const iconsList = ${JSON.stringify(combinedIcons)};
    export type IconName = ${combinedIcons.map((icon) => `'${icon}'`).join(' | ')};
  `
  fs.writeFileSync(outputPath, fileContent, 'utf-8')
}
